@startuml
class Caretaker {
    + Caretaker(originator:Originator)
    + resetRedo() : void
    + Backup() : void
    + BackupIncludingNew() : void
    + Undo() : string
    + Redo() : string
    + checkIfEqual(input:string) : bool
    + checkMementoState() : string
    + checkRedoState() : string
    + printUndoList() : void
    + printRedoList() : void
}
@enduml
