@startuml
class Ellipse {
    + ex : string?
    + ey : string?
    + er1 : string?
    + er2 : string?
    + ellipseFill : string?
    + ellipseStroke : string?
    + ellipseStrokeWidth : string?
    + Ellipse(ex:string?, ey:string?, er1:string?, er2:string?, ellipseFill:string?, ellipseStroke:string?, ellipseStrokeWidth:string?)
    + <<override>> ToString() : string
}
Shape <|-- Ellipse
@enduml
