@startuml
class Line {
    + x1 : string?
    + y1 : string?
    + x2 : string?
    + y2 : string?
    + lineStroke : string?
    + lineStrokeWidth : string?
    + Line(x1:string?, y1:string?, x2:string?, y2:string?, lineStroke:string?, lineStrokeWidth:string?)
    + <<override>> ToString() : string
}
Shape <|-- Line
@enduml
