@startuml
class Path {
    + path : string?
    + pathStroke : string?
    + pathStrokeWidth : string?
    + pathStrokeFill : string?
    + Path(path:string?, pathStroke:string?, pathStrokeWidth:string?, pathStrokeFill:string?)
    + <<override>> ToString() : string
}
Shape <|-- Path
@enduml
