@startuml
class Polyline {
    + points : string?
    + polylineFill : string?
    + polylineStroke : string?
    + polylineStrokeWidth : string?
    + Polyline(points:string?, polylineFill:string?, polylineStroke:string?, polylineStrokeWidth:string?)
    + <<override>> ToString() : string
}
Shape <|-- Polyline
@enduml
